# Generated by Django 2.2.6 on 2025-09-10 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date_approved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
